<?php
/**
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  CristianoPacheco
 * @package   CristianoPacheco_ModuleBase
 *
 * @copyright Copyright (c) 2019 Cristiano Pacheco - (https://www.linkedin.com/in/cristiano-pacheco/)
 *
 * @author    Cristiano Pacheco <contato@cristianopacheco.com.br>
 */

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(ComponentRegistrar::MODULE, 'CristianoPacheco_ModuleBase', __DIR__);
